name: build api

on:
  page_build

jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: Test
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.API_KEY }}
        run: |
          cd services && echo -e 'export let apiKey = "$SUPER_SECRET"';
